//#line 2 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the pgr_camera_driver package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __pgr_camera_driver__PGRCAMERACONFIG_H__
#define __pgr_camera_driver__PGRCAMERACONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace pgr_camera_driver
{
  class PGRCameraConfigStatics;
  
  class PGRCameraConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(PGRCameraConfig &config, const PGRCameraConfig &max, const PGRCameraConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const PGRCameraConfig &config1, const PGRCameraConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, PGRCameraConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const PGRCameraConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PGRCameraConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const PGRCameraConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T PGRCameraConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (PGRCameraConfig::* field);

      virtual void clamp(PGRCameraConfig &config, const PGRCameraConfig &max, const PGRCameraConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const PGRCameraConfig &config1, const PGRCameraConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, PGRCameraConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const PGRCameraConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PGRCameraConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const PGRCameraConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 18 "../cfg/PGRCamera.cfg"
      std::string trigger_mode;
//#line 19 "../cfg/PGRCamera.cfg"
      bool auto_exposure;
//#line 20 "../cfg/PGRCamera.cfg"
      bool auto_shutter;
//#line 21 "../cfg/PGRCamera.cfg"
      double shutter;
//#line 22 "../cfg/PGRCamera.cfg"
      bool auto_gain;
//#line 23 "../cfg/PGRCamera.cfg"
      double gain;
//#line 24 "../cfg/PGRCamera.cfg"
      bool auto_whitebalance;
//#line 25 "../cfg/PGRCamera.cfg"
      int whitebalance_red;
//#line 26 "../cfg/PGRCamera.cfg"
      int whitebalance_blue;
//#line 28 "../cfg/PGRCamera.cfg"
      std::string frame_id;
//#line 29 "../cfg/PGRCamera.cfg"
      int roi_x_offset;
//#line 30 "../cfg/PGRCamera.cfg"
      int roi_y_offset;
//#line 31 "../cfg/PGRCamera.cfg"
      int roi_width;
//#line 32 "../cfg/PGRCamera.cfg"
      int roi_height;
//#line 34 "../cfg/PGRCamera.cfg"
      int width;
//#line 35 "../cfg/PGRCamera.cfg"
      int height;
//#line 36 "../cfg/PGRCamera.cfg"
      std::string format;
//#line 37 "../cfg/PGRCamera.cfg"
      double frame_rate;
//#line 38 "../cfg/PGRCamera.cfg"
      std::string intrinsics_ini;
//#line 39 "../cfg/PGRCamera.cfg"
      std::string camera_name;
//#line 138 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("PGRCameraConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const PGRCameraConfig &__max__ = __getMax__();
      const PGRCameraConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const PGRCameraConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const PGRCameraConfig &__getDefault__();
    static const PGRCameraConfig &__getMax__();
    static const PGRCameraConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const PGRCameraConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void PGRCameraConfig::ParamDescription<std::string>::clamp(PGRCameraConfig &config, const PGRCameraConfig &max, const PGRCameraConfig &min) const
  {
    return;
  }

  class PGRCameraConfigStatics
  {
    friend class PGRCameraConfig;
    
    PGRCameraConfigStatics()
    {
//#line 18 "../cfg/PGRCamera.cfg"
      __min__.trigger_mode = "";
//#line 18 "../cfg/PGRCamera.cfg"
      __max__.trigger_mode = "";
//#line 18 "../cfg/PGRCamera.cfg"
      __default__.trigger_mode = "streaming";
//#line 18 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<std::string>("trigger_mode", "str", 1, "Camera mode (streaming vs. polled)", "{'enum_description': 'Enum to set the mode.', 'enum': [{'srcline': 13, 'description': 'Streaming mode', 'srcfile': '../cfg/PGRCamera.cfg', 'cconsttype': 'const char * const', 'value': 'streaming', 'ctype': 'std::string', 'type': 'str', 'name': 'StreamingMode'}, {'srcline': 14, 'description': 'Polled mode', 'srcfile': '../cfg/PGRCamera.cfg', 'cconsttype': 'const char * const', 'value': 'polled', 'ctype': 'std::string', 'type': 'str', 'name': 'PolledMode'}]}", &PGRCameraConfig::trigger_mode)));
//#line 19 "../cfg/PGRCamera.cfg"
      __min__.auto_exposure = 0;
//#line 19 "../cfg/PGRCamera.cfg"
      __max__.auto_exposure = 1;
//#line 19 "../cfg/PGRCamera.cfg"
      __default__.auto_exposure = 1;
//#line 19 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<bool>("auto_exposure", "bool", 0, "Sets the camera exposure duration to automatic. Causes the @b exposure setting to be ignored.", "", &PGRCameraConfig::auto_exposure)));
//#line 20 "../cfg/PGRCamera.cfg"
      __min__.auto_shutter = 0;
//#line 20 "../cfg/PGRCamera.cfg"
      __max__.auto_shutter = 1;
//#line 20 "../cfg/PGRCamera.cfg"
      __default__.auto_shutter = 1;
//#line 20 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<bool>("auto_shutter", "bool", 0, "Sets the camera shutter speed to automatic. Allows the auto-exposure to adjust as necessary.", "", &PGRCameraConfig::auto_shutter)));
//#line 21 "../cfg/PGRCamera.cfg"
      __min__.shutter = 0.0;
//#line 21 "../cfg/PGRCamera.cfg"
      __max__.shutter = 1.0;
//#line 21 "../cfg/PGRCamera.cfg"
      __default__.shutter = 0.05;
//#line 21 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<double>("shutter", "double", 0, "Camera shutter length in seconds.", "", &PGRCameraConfig::shutter)));
//#line 22 "../cfg/PGRCamera.cfg"
      __min__.auto_gain = 0;
//#line 22 "../cfg/PGRCamera.cfg"
      __max__.auto_gain = 1;
//#line 22 "../cfg/PGRCamera.cfg"
      __default__.auto_gain = 1;
//#line 22 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<bool>("auto_gain", "bool", 0, "Sets the analog gain to automatic. Causes the @b gain setting to be ignored.", "", &PGRCameraConfig::auto_gain)));
//#line 23 "../cfg/PGRCamera.cfg"
      __min__.gain = 0.0;
//#line 23 "../cfg/PGRCamera.cfg"
      __max__.gain = 24.0;
//#line 23 "../cfg/PGRCamera.cfg"
      __default__.gain = 24.0;
//#line 23 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<double>("gain", "double", 0, "The gain level in dB.", "", &PGRCameraConfig::gain)));
//#line 24 "../cfg/PGRCamera.cfg"
      __min__.auto_whitebalance = 0;
//#line 24 "../cfg/PGRCamera.cfg"
      __max__.auto_whitebalance = 1;
//#line 24 "../cfg/PGRCamera.cfg"
      __default__.auto_whitebalance = 1;
//#line 24 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<bool>("auto_whitebalance", "bool", 0, "Whether whitebalance will continuously adjust to the current scene. Causes the @b whitebalance_red and @b whitebalance_blue settings to be ignored.", "", &PGRCameraConfig::auto_whitebalance)));
//#line 25 "../cfg/PGRCamera.cfg"
      __min__.whitebalance_red = 0;
//#line 25 "../cfg/PGRCamera.cfg"
      __max__.whitebalance_red = 100;
//#line 25 "../cfg/PGRCamera.cfg"
      __default__.whitebalance_red = 0;
//#line 25 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<int>("whitebalance_red", "int", 0, "Red gain as a percentage of the camera default setting.", "", &PGRCameraConfig::whitebalance_red)));
//#line 26 "../cfg/PGRCamera.cfg"
      __min__.whitebalance_blue = 0;
//#line 26 "../cfg/PGRCamera.cfg"
      __max__.whitebalance_blue = 100;
//#line 26 "../cfg/PGRCamera.cfg"
      __default__.whitebalance_blue = 0;
//#line 26 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<int>("whitebalance_blue", "int", 0, "Blue gain as a percentage of the camera default setting.", "", &PGRCameraConfig::whitebalance_blue)));
//#line 28 "../cfg/PGRCamera.cfg"
      __min__.frame_id = "";
//#line 28 "../cfg/PGRCamera.cfg"
      __max__.frame_id = "";
//#line 28 "../cfg/PGRCamera.cfg"
      __default__.frame_id = "pgr_camera_frame";
//#line 28 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<std::string>("frame_id", "str", 0, "The optical camera TF frame set in message headers.", "", &PGRCameraConfig::frame_id)));
//#line 29 "../cfg/PGRCamera.cfg"
      __min__.roi_x_offset = 0;
//#line 29 "../cfg/PGRCamera.cfg"
      __max__.roi_x_offset = 4000;
//#line 29 "../cfg/PGRCamera.cfg"
      __default__.roi_x_offset = 0;
//#line 29 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<int>("roi_x_offset", "int", 0, "X offset of the region of interest.", "", &PGRCameraConfig::roi_x_offset)));
//#line 30 "../cfg/PGRCamera.cfg"
      __min__.roi_y_offset = 0;
//#line 30 "../cfg/PGRCamera.cfg"
      __max__.roi_y_offset = 4000;
//#line 30 "../cfg/PGRCamera.cfg"
      __default__.roi_y_offset = 0;
//#line 30 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<int>("roi_y_offset", "int", 0, "Y offset of the region of interest.", "", &PGRCameraConfig::roi_y_offset)));
//#line 31 "../cfg/PGRCamera.cfg"
      __min__.roi_width = 0;
//#line 31 "../cfg/PGRCamera.cfg"
      __max__.roi_width = 4000;
//#line 31 "../cfg/PGRCamera.cfg"
      __default__.roi_width = 0;
//#line 31 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<int>("roi_width", "int", 0, "Width of the region of interest (0 for automatic).", "", &PGRCameraConfig::roi_width)));
//#line 32 "../cfg/PGRCamera.cfg"
      __min__.roi_height = 0;
//#line 32 "../cfg/PGRCamera.cfg"
      __max__.roi_height = 4000;
//#line 32 "../cfg/PGRCamera.cfg"
      __default__.roi_height = 0;
//#line 32 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<int>("roi_height", "int", 0, "Height of the region of interest (0 for automatic).", "", &PGRCameraConfig::roi_height)));
//#line 34 "../cfg/PGRCamera.cfg"
      __min__.width = 640;
//#line 34 "../cfg/PGRCamera.cfg"
      __max__.width = 1296;
//#line 34 "../cfg/PGRCamera.cfg"
      __default__.width = 1280;
//#line 34 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<int>("width", "int", 0, "Capture width", "", &PGRCameraConfig::width)));
//#line 35 "../cfg/PGRCamera.cfg"
      __min__.height = 480;
//#line 35 "../cfg/PGRCamera.cfg"
      __max__.height = 964;
//#line 35 "../cfg/PGRCamera.cfg"
      __default__.height = 960;
//#line 35 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<int>("height", "int", 0, "Capture height", "", &PGRCameraConfig::height)));
//#line 36 "../cfg/PGRCamera.cfg"
      __min__.format = "";
//#line 36 "../cfg/PGRCamera.cfg"
      __max__.format = "";
//#line 36 "../cfg/PGRCamera.cfg"
      __default__.format = "Y8";
//#line 36 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<std::string>("format", "str", 0, "Capture format (Y8,RGB). Y8 can handle color (Don't Select RGB if you don't know the supported formats)", "{'enum_description': 'Enum to set the format.', 'enum': [{'srcline': 15, 'description': 'Y8 mode', 'srcfile': '../cfg/PGRCamera.cfg', 'cconsttype': 'const char * const', 'value': 'Y8', 'ctype': 'std::string', 'type': 'str', 'name': 'Y8'}, {'srcline': 16, 'description': 'RGB mode', 'srcfile': '../cfg/PGRCamera.cfg', 'cconsttype': 'const char * const', 'value': 'RGB', 'ctype': 'std::string', 'type': 'str', 'name': 'RGB'}]}", &PGRCameraConfig::format)));
//#line 37 "../cfg/PGRCamera.cfg"
      __min__.frame_rate = 1.151;
//#line 37 "../cfg/PGRCamera.cfg"
      __max__.frame_rate = 60.861;
//#line 37 "../cfg/PGRCamera.cfg"
      __default__.frame_rate = 15.0;
//#line 37 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<double>("frame_rate", "double", 0, "Camera frame rate in Hz.", "", &PGRCameraConfig::frame_rate)));
//#line 38 "../cfg/PGRCamera.cfg"
      __min__.intrinsics_ini = "";
//#line 38 "../cfg/PGRCamera.cfg"
      __max__.intrinsics_ini = "";
//#line 38 "../cfg/PGRCamera.cfg"
      __default__.intrinsics_ini = "test_intrinsics.ini";
//#line 38 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<std::string>("intrinsics_ini", "str", 0, "Camera intrinsics INI filename", "", &PGRCameraConfig::intrinsics_ini)));
//#line 39 "../cfg/PGRCamera.cfg"
      __min__.camera_name = "";
//#line 39 "../cfg/PGRCamera.cfg"
      __max__.camera_name = "";
//#line 39 "../cfg/PGRCamera.cfg"
      __default__.camera_name = "pgr_camera";
//#line 39 "../cfg/PGRCamera.cfg"
      __param_descriptions__.push_back(PGRCameraConfig::AbstractParamDescriptionConstPtr(new PGRCameraConfig::ParamDescription<std::string>("camera_name", "str", 0, "Camera Name (used in loading intrinsics INI)", "", &PGRCameraConfig::camera_name)));
//#line 239 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<PGRCameraConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<PGRCameraConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    PGRCameraConfig __max__;
    PGRCameraConfig __min__;
    PGRCameraConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const PGRCameraConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static PGRCameraConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &PGRCameraConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const PGRCameraConfig &PGRCameraConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const PGRCameraConfig &PGRCameraConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const PGRCameraConfig &PGRCameraConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<PGRCameraConfig::AbstractParamDescriptionConstPtr> &PGRCameraConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const PGRCameraConfigStatics *PGRCameraConfig::__get_statics__()
  {
    const static PGRCameraConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = PGRCameraConfigStatics::get_instance();
    
    return statics;
  }

//#line 13 "../cfg/PGRCamera.cfg"
      const char * const PGRCamera_StreamingMode = "streaming";
//#line 14 "../cfg/PGRCamera.cfg"
      const char * const PGRCamera_PolledMode = "polled";
//#line 15 "../cfg/PGRCamera.cfg"
      const char * const PGRCamera_Y8 = "Y8";
//#line 16 "../cfg/PGRCamera.cfg"
      const char * const PGRCamera_RGB = "RGB";
}

#endif // __PGRCAMERARECONFIGURATOR_H__
